server:
    port: 9090
        
spring: 
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.72:3306/tom?autoReconnect=true
        username: root
        password: root

mybatis: 
    mapperLocations: classpath*:xml/**/*.xml
    typeAliasesPackage: com.open.yun.ysmsvs.model
    basePackage: com.open.yun.ysmsvs.mapper
      
logging:  
    file: /var/open/common/info.log
