package com.open.yun.ysmsvs.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.名称
     *
     * @mbggenerated
     */
    private String 名称;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.访问地址
     *
     * @mbggenerated
     */
    private String 访问地址;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.账号
     *
     * @mbggenerated
     */
    private String 账号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.密码
     *
     * @mbggenerated
     */
    private String 密码;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.备用字段1
     *
     * @mbggenerated
     */
    private String 备用字段1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.备用字段2
     *
     * @mbggenerated
     */
    private String 备用字段2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.备用字段3
     *
     * @mbggenerated
     */
    private String 备用字段3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.名称
     *
     * @return the value of account.名称
     *
     * @mbggenerated
     */
    public String get名称() {
        return 名称;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.名称
     *
     * @param 名称 the value for account.名称
     *
     * @mbggenerated
     */
    public void set名称(String 名称) {
        this.名称 = 名称 == null ? null : 名称.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.访问地址
     *
     * @return the value of account.访问地址
     *
     * @mbggenerated
     */
    public String get访问地址() {
        return 访问地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.访问地址
     *
     * @param 访问地址 the value for account.访问地址
     *
     * @mbggenerated
     */
    public void set访问地址(String 访问地址) {
        this.访问地址 = 访问地址 == null ? null : 访问地址.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.账号
     *
     * @return the value of account.账号
     *
     * @mbggenerated
     */
    public String get账号() {
        return 账号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.账号
     *
     * @param 账号 the value for account.账号
     *
     * @mbggenerated
     */
    public void set账号(String 账号) {
        this.账号 = 账号 == null ? null : 账号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.密码
     *
     * @return the value of account.密码
     *
     * @mbggenerated
     */
    public String get密码() {
        return 密码;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.密码
     *
     * @param 密码 the value for account.密码
     *
     * @mbggenerated
     */
    public void set密码(String 密码) {
        this.密码 = 密码 == null ? null : 密码.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.备用字段1
     *
     * @return the value of account.备用字段1
     *
     * @mbggenerated
     */
    public String get备用字段1() {
        return 备用字段1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.备用字段1
     *
     * @param 备用字段1 the value for account.备用字段1
     *
     * @mbggenerated
     */
    public void set备用字段1(String 备用字段1) {
        this.备用字段1 = 备用字段1 == null ? null : 备用字段1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.备用字段2
     *
     * @return the value of account.备用字段2
     *
     * @mbggenerated
     */
    public String get备用字段2() {
        return 备用字段2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.备用字段2
     *
     * @param 备用字段2 the value for account.备用字段2
     *
     * @mbggenerated
     */
    public void set备用字段2(String 备用字段2) {
        this.备用字段2 = 备用字段2 == null ? null : 备用字段2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.备用字段3
     *
     * @return the value of account.备用字段3
     *
     * @mbggenerated
     */
    public String get备用字段3() {
        return 备用字段3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.备用字段3
     *
     * @param 备用字段3 the value for account.备用字段3
     *
     * @mbggenerated
     */
    public void set备用字段3(String 备用字段3) {
        this.备用字段3 = 备用字段3 == null ? null : 备用字段3.trim();
    }
}