package com.open.yun.ysmsvs.model;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Byte value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Byte value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Byte value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Byte value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Byte value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Byte> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Byte> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Byte value1, Byte value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Byte value1, Byte value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and名称IsNull() {
            addCriterion("名称 is null");
            return (Criteria) this;
        }

        public Criteria and名称IsNotNull() {
            addCriterion("名称 is not null");
            return (Criteria) this;
        }

        public Criteria and名称EqualTo(String value) {
            addCriterion("名称 =", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称NotEqualTo(String value) {
            addCriterion("名称 <>", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称GreaterThan(String value) {
            addCriterion("名称 >", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称GreaterThanOrEqualTo(String value) {
            addCriterion("名称 >=", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称LessThan(String value) {
            addCriterion("名称 <", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称LessThanOrEqualTo(String value) {
            addCriterion("名称 <=", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称Like(String value) {
            addCriterion("名称 like", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称NotLike(String value) {
            addCriterion("名称 not like", value, "名称");
            return (Criteria) this;
        }

        public Criteria and名称In(List<String> values) {
            addCriterion("名称 in", values, "名称");
            return (Criteria) this;
        }

        public Criteria and名称NotIn(List<String> values) {
            addCriterion("名称 not in", values, "名称");
            return (Criteria) this;
        }

        public Criteria and名称Between(String value1, String value2) {
            addCriterion("名称 between", value1, value2, "名称");
            return (Criteria) this;
        }

        public Criteria and名称NotBetween(String value1, String value2) {
            addCriterion("名称 not between", value1, value2, "名称");
            return (Criteria) this;
        }

        public Criteria and访问地址IsNull() {
            addCriterion("访问地址 is null");
            return (Criteria) this;
        }

        public Criteria and访问地址IsNotNull() {
            addCriterion("访问地址 is not null");
            return (Criteria) this;
        }

        public Criteria and访问地址EqualTo(String value) {
            addCriterion("访问地址 =", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址NotEqualTo(String value) {
            addCriterion("访问地址 <>", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址GreaterThan(String value) {
            addCriterion("访问地址 >", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址GreaterThanOrEqualTo(String value) {
            addCriterion("访问地址 >=", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址LessThan(String value) {
            addCriterion("访问地址 <", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址LessThanOrEqualTo(String value) {
            addCriterion("访问地址 <=", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址Like(String value) {
            addCriterion("访问地址 like", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址NotLike(String value) {
            addCriterion("访问地址 not like", value, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址In(List<String> values) {
            addCriterion("访问地址 in", values, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址NotIn(List<String> values) {
            addCriterion("访问地址 not in", values, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址Between(String value1, String value2) {
            addCriterion("访问地址 between", value1, value2, "访问地址");
            return (Criteria) this;
        }

        public Criteria and访问地址NotBetween(String value1, String value2) {
            addCriterion("访问地址 not between", value1, value2, "访问地址");
            return (Criteria) this;
        }

        public Criteria and账号IsNull() {
            addCriterion("账号 is null");
            return (Criteria) this;
        }

        public Criteria and账号IsNotNull() {
            addCriterion("账号 is not null");
            return (Criteria) this;
        }

        public Criteria and账号EqualTo(String value) {
            addCriterion("账号 =", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号NotEqualTo(String value) {
            addCriterion("账号 <>", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号GreaterThan(String value) {
            addCriterion("账号 >", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号GreaterThanOrEqualTo(String value) {
            addCriterion("账号 >=", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号LessThan(String value) {
            addCriterion("账号 <", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号LessThanOrEqualTo(String value) {
            addCriterion("账号 <=", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号Like(String value) {
            addCriterion("账号 like", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号NotLike(String value) {
            addCriterion("账号 not like", value, "账号");
            return (Criteria) this;
        }

        public Criteria and账号In(List<String> values) {
            addCriterion("账号 in", values, "账号");
            return (Criteria) this;
        }

        public Criteria and账号NotIn(List<String> values) {
            addCriterion("账号 not in", values, "账号");
            return (Criteria) this;
        }

        public Criteria and账号Between(String value1, String value2) {
            addCriterion("账号 between", value1, value2, "账号");
            return (Criteria) this;
        }

        public Criteria and账号NotBetween(String value1, String value2) {
            addCriterion("账号 not between", value1, value2, "账号");
            return (Criteria) this;
        }

        public Criteria and密码IsNull() {
            addCriterion("密码 is null");
            return (Criteria) this;
        }

        public Criteria and密码IsNotNull() {
            addCriterion("密码 is not null");
            return (Criteria) this;
        }

        public Criteria and密码EqualTo(String value) {
            addCriterion("密码 =", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码NotEqualTo(String value) {
            addCriterion("密码 <>", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码GreaterThan(String value) {
            addCriterion("密码 >", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码GreaterThanOrEqualTo(String value) {
            addCriterion("密码 >=", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码LessThan(String value) {
            addCriterion("密码 <", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码LessThanOrEqualTo(String value) {
            addCriterion("密码 <=", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码Like(String value) {
            addCriterion("密码 like", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码NotLike(String value) {
            addCriterion("密码 not like", value, "密码");
            return (Criteria) this;
        }

        public Criteria and密码In(List<String> values) {
            addCriterion("密码 in", values, "密码");
            return (Criteria) this;
        }

        public Criteria and密码NotIn(List<String> values) {
            addCriterion("密码 not in", values, "密码");
            return (Criteria) this;
        }

        public Criteria and密码Between(String value1, String value2) {
            addCriterion("密码 between", value1, value2, "密码");
            return (Criteria) this;
        }

        public Criteria and密码NotBetween(String value1, String value2) {
            addCriterion("密码 not between", value1, value2, "密码");
            return (Criteria) this;
        }

        public Criteria and备用字段1IsNull() {
            addCriterion("备用字段1 is null");
            return (Criteria) this;
        }

        public Criteria and备用字段1IsNotNull() {
            addCriterion("备用字段1 is not null");
            return (Criteria) this;
        }

        public Criteria and备用字段1EqualTo(String value) {
            addCriterion("备用字段1 =", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1NotEqualTo(String value) {
            addCriterion("备用字段1 <>", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1GreaterThan(String value) {
            addCriterion("备用字段1 >", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1GreaterThanOrEqualTo(String value) {
            addCriterion("备用字段1 >=", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1LessThan(String value) {
            addCriterion("备用字段1 <", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1LessThanOrEqualTo(String value) {
            addCriterion("备用字段1 <=", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1Like(String value) {
            addCriterion("备用字段1 like", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1NotLike(String value) {
            addCriterion("备用字段1 not like", value, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1In(List<String> values) {
            addCriterion("备用字段1 in", values, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1NotIn(List<String> values) {
            addCriterion("备用字段1 not in", values, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1Between(String value1, String value2) {
            addCriterion("备用字段1 between", value1, value2, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段1NotBetween(String value1, String value2) {
            addCriterion("备用字段1 not between", value1, value2, "备用字段1");
            return (Criteria) this;
        }

        public Criteria and备用字段2IsNull() {
            addCriterion("备用字段2 is null");
            return (Criteria) this;
        }

        public Criteria and备用字段2IsNotNull() {
            addCriterion("备用字段2 is not null");
            return (Criteria) this;
        }

        public Criteria and备用字段2EqualTo(String value) {
            addCriterion("备用字段2 =", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2NotEqualTo(String value) {
            addCriterion("备用字段2 <>", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2GreaterThan(String value) {
            addCriterion("备用字段2 >", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2GreaterThanOrEqualTo(String value) {
            addCriterion("备用字段2 >=", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2LessThan(String value) {
            addCriterion("备用字段2 <", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2LessThanOrEqualTo(String value) {
            addCriterion("备用字段2 <=", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2Like(String value) {
            addCriterion("备用字段2 like", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2NotLike(String value) {
            addCriterion("备用字段2 not like", value, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2In(List<String> values) {
            addCriterion("备用字段2 in", values, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2NotIn(List<String> values) {
            addCriterion("备用字段2 not in", values, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2Between(String value1, String value2) {
            addCriterion("备用字段2 between", value1, value2, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段2NotBetween(String value1, String value2) {
            addCriterion("备用字段2 not between", value1, value2, "备用字段2");
            return (Criteria) this;
        }

        public Criteria and备用字段3IsNull() {
            addCriterion("备用字段3 is null");
            return (Criteria) this;
        }

        public Criteria and备用字段3IsNotNull() {
            addCriterion("备用字段3 is not null");
            return (Criteria) this;
        }

        public Criteria and备用字段3EqualTo(String value) {
            addCriterion("备用字段3 =", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3NotEqualTo(String value) {
            addCriterion("备用字段3 <>", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3GreaterThan(String value) {
            addCriterion("备用字段3 >", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3GreaterThanOrEqualTo(String value) {
            addCriterion("备用字段3 >=", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3LessThan(String value) {
            addCriterion("备用字段3 <", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3LessThanOrEqualTo(String value) {
            addCriterion("备用字段3 <=", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3Like(String value) {
            addCriterion("备用字段3 like", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3NotLike(String value) {
            addCriterion("备用字段3 not like", value, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3In(List<String> values) {
            addCriterion("备用字段3 in", values, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3NotIn(List<String> values) {
            addCriterion("备用字段3 not in", values, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3Between(String value1, String value2) {
            addCriterion("备用字段3 between", value1, value2, "备用字段3");
            return (Criteria) this;
        }

        public Criteria and备用字段3NotBetween(String value1, String value2) {
            addCriterion("备用字段3 not between", value1, value2, "备用字段3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}